language: php
os:
  - linux
dist: bionic

php:
  - 7.3
  - 7.2
  - 7.1

jobs:
  include:
    - name: "Downgrade from PHP 7.4 to PHP 7.3"
      php: 7.4
      script:
        - composer run-script downgrade-upstream

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer update -v

script:
  - composer run-script analyze
